# Generated by Django 4.2.9 on 2026-01-21 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('aga_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('aga_rank', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_color', models.CharField(choices=[('black', 'Black'), ('white', 'White')], max_length=5)),
                ('player2_color', models.CharField(choices=[('black', 'Black'), ('white', 'White')], max_length=5)),
                ('handicap', models.IntegerField(default=0)),
                ('rated', models.BooleanField(default=True)),
                ('winner', models.CharField(choices=[('player1', 'Player 1'), ('player2', 'Player 2')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player1', to='tournament.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player2', to='tournament.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
